<?php

/**
 * @file
 * Custom Theme theme file.
 */
function custom_theme_preprocess_html(&$variables) {
    // Get current node url.
    $node_url = \Drupal::request()->getRequestUri();
    // Check whether the node url is of required node or not.
    if ($node_url === '') {
      // Attach the custom_theme/custom-render library to the page.
     
      $variables['#attached']['library'][] = 'custom_theme/slider';
    }
  }